stages:
  get-squad1-train:
    cmd: wget https://rajpurkar.github.io/SQuAD-explorer/dataset/train-v1.1.json -O
      data/datasets/squad1/train-v1.1.json
    outs:
    - data/datasets/squad1/train-v1.1.json
    frozen: true
  get-squad1-dev:
    cmd: wget https://rajpurkar.github.io/SQuAD-explorer/dataset/dev-v1.1.json -O
      data/datasets/squad1/dev-v1.1.json
    outs:
    - data/datasets/squad1/dev-v1.1.json
    frozen: true
